### ISSUE TITLE
Upstream merge tasks

### ISSUE THREAD

**Issue by johnrchrdsn** [jimboatarm/workload-automation#165]
Features implemented to support upstreaming:
- [x] Switch FPS logging from UiAutomator dumpsys to using the FPS instrumentation with a "marker" API — ARM-software#201, ARM-software#212
- [x] APK version checking and support for min/max version supported by a workload — ARM-software#190, ARM-software#238
- [x] Check network connectivity as per https://github.com/jimboatarm/workload-automation/commit/69db2f2f41a679db6865ccc693b3b350336d943c — ARM-software#214, ARM-software#237
- [x] Dump view hierachy as per https://github.com/jimboatarm/workload-automation/commit/d6afc6d3a1f88614e5a8156a001980ef95ce70bc — ARM-software#217
- [x] Base class libraries update and `target-sdk` version bump to 18 across the board – ARM-software#213
- [x] Use content resolvers for external file dependencies and add default assets for them — #168

For each workload class, these changes have to be made:
1. Inherit from `AndroidUxPerfWorkload` to get additional functionality such as asset management, and enabling the uxperf marker API
2. Remove `dumpsys_enabled` param - now covered by `markers_enabled` in `AndroidUxPerfWorkload`
3. Remove functionality related to pulling logs and updating metrics
4. Add any assets to be pushed to device to the `deployable_assets` list (see `googlephotos` or `googleslides` workload for examples)
5. Where applicable, add `min_apk_version` and `max_apk_version` attributes that specify the lowest and highest versions of the APK tested/supported by the workload.
6. Remove the `Timer` and replace calls to `SurfaceLogger`/`{start,stop}Dumpsys` with the `ActionLogger`
7. ~~Update `__version__` attribute to 1.0.0~~ (N/A for upstream) – should be removed if present

**Comment by muendelezaji** [comment]
Workloads for upstreaming:
- [ ] excel*
- [ ] gmail*
- [x] googlephotos*
- [x] googleplaybooks
- [x] googleslides*
- [ ] msword*
- [ ] powerpoint*
- [ ] reader*
- [x] skype
- [x] youtube
- [ ] multiapp†

`*` = has external dependencies
`†` = TBD

**Comment by muendelezaji** [comment]
### Versions

App versions for workloads in master branch. Note that some apps have an extra version specifier for different ABI variants (commented out).

``` python
1. excel
    package = 'com.microsoft.office.excel'  
    version = '16.0.6925.1017'

2. gmail
    package = 'com.google.android.gm'  
    version = '6.7.128801648'

3. googlephotos
    package = 'com.google.android.apps.photos'  
    version = '1.21.0.123444480'

4. googleplaybooks
    package = 'com.google.android.apps.books'  
    version = '3.9.37'

5. googleslides
    package = 'com.google.android.apps.docs.editors.slides'  
    version = '1.6.312.08.32'

6. msword
    package = 'com.microsoft.office.word'  
    version = '16.0.6925.1017'

7. powerpoint
    package = 'com.microsoft.office.powerpoint'  
    version = '16.0.6925.1017'

8. reader
    package = 'com.adobe.reader'  
    version = '16.1.1'

9. skype
    package = 'com.skype.raider'  
    version = '7.01.0.669'

10. youtube
    package = 'com.google.android.youtube'  
    version = '11.19.56'
```
